/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description List all books in the library
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ListBooksResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest book scans
         * @description Ingest PDF files as a new book and start processing
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Ingest request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_endpoints.IngestRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.IngestResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and ingest book PDFs
         * @description Upload PDF files to ingest as a new book
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description PDF files to ingest
                         */
                        files: string;
                        /** @description Book title (derived from filename if not provided) */
                        title?: string;
                        /** @description Book author */
                        author?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.IngestResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pages
         * @description List all pages for a book with processing status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    book_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ListPagesResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/{page_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get page details
         * @description Get full details for a specific page including OCR results, blend output, and labels
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    book_id: string;
                    /** @description Page number (1-indexed) */
                    page_num: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.GetPageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/{page_num}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get page image
         * @description Get the PNG image for a specific page of a book
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    book_id: string;
                    /** @description Page number (1-indexed) */
                    page_num: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get book by ID
         * @description Get detailed information about a book
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.Book"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get book processing cost
         * @description Get total cost for processing a specific book
         */
        get: {
            parameters: {
                query?: {
                    /** @description Breakdown by: stage */
                    by?: string;
                };
                header?: never;
                path: {
                    /** @description Book ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.MetricsCostResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description List all jobs with optional filtering
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by status */
                    status?: string;
                    /** @description Filter by job type */
                    job_type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ListJobsResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a job
         * @description Create a new job of the specified type
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Job creation request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_endpoints.CreateJobRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.CreateJobResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/start/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start job for a book
         * @description Start processing job (OCR, blend, label) for a book
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    book_id: string;
                };
                cookie?: never;
            };
            /** @description Optional job type */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["internal_server_endpoints.StartJobRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.StartJobResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/status/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job status for a book
         * @description Get processing status for a book's jobs
         */
        get: {
            parameters: {
                query?: {
                    /** @description Job type (default: process-pages) */
                    job_type?: string;
                };
                header?: never;
                path: {
                    /** @description Book ID */
                    book_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.JobStatusResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job by ID
         * @description Get detailed job information including live status for running jobs
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.GetJobResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a job
         * @description Delete a job by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a job
         * @description Update job status or metadata
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_endpoints.UpdateJobRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.Record"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List metrics
         * @description List LLM/OCR call metrics with optional filtering
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by job ID */
                    job_id?: string;
                    /** @description Filter by book ID */
                    book_id?: string;
                    /** @description Filter by stage */
                    stage?: string;
                    /** @description Filter by provider */
                    provider?: string;
                    /** @description Filter by model */
                    model?: string;
                    /** @description Maximum results (default 100) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ListMetricsResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cost breakdown
         * @description Get total cost with optional breakdown by stage/provider/model
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by job ID */
                    job_id?: string;
                    /** @description Filter by book ID */
                    book_id?: string;
                    /** @description Filter by stage */
                    stage?: string;
                    /** @description Filter by provider */
                    provider?: string;
                    /** @description Filter by model */
                    model?: string;
                    /** @description Breakdown by: stage, provider, or model */
                    by?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.MetricsCostResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metrics summary
         * @description Get aggregated metrics summary with counts, costs, and timing
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by job ID */
                    job_id?: string;
                    /** @description Filter by book ID */
                    book_id?: string;
                    /** @description Filter by stage */
                    stage?: string;
                    /** @description Filter by provider */
                    provider?: string;
                    /** @description Filter by model */
                    model?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.MetricsSummaryResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Basic health check endpoint
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Readiness check including DefraDB status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.HealthResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server status
         * @description Get detailed server status including providers and DefraDB
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_endpoints.StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_jackzampolin_shelf_internal_jobs.ProviderProgress": {
            /** @description Completed during this job execution */
            completed?: number;
            /** @description Already completed before job started (from DefraDB) */
            completedAtStart?: number;
            /** @description Failed during this job execution */
            failed?: number;
            /** @description Currently queued/in-flight */
            queued?: number;
            /** @description Total work units expected for this provider */
            totalExpected?: number;
        };
        "github_com_jackzampolin_shelf_internal_jobs.Record": {
            _docID?: string;
            completed_at?: string;
            created_at?: string;
            error?: string;
            job_type?: string;
            metadata?: {
                [key: string]: unknown;
            };
            started_at?: string;
            status?: components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.Status"];
        };
        /** @enum {string} */
        "github_com_jackzampolin_shelf_internal_jobs.Status": "queued" | "running" | "completed" | "failed" | "cancelled";
        "github_com_jackzampolin_shelf_internal_jobs.WorkerStatusInfo": {
            queue_depth?: number;
            rate_limiter?: components["schemas"]["github_com_jackzampolin_shelf_internal_providers.RateLimiterStatus"];
            type?: string;
        };
        "github_com_jackzampolin_shelf_internal_metrics.Metric": {
            _docID?: string;
            book_id?: string;
            completion_tokens?: number;
            /** @description Cost and tokens */
            cost_usd?: number;
            /** @description Metadata */
            created_at?: string;
            error_type?: string;
            execution_seconds?: number;
            /** @description e.g., "page_0001", "toc_entry_5" */
            item_key?: string;
            /** @description Attribution (for filtering/aggregation) */
            job_id?: string;
            model?: string;
            /** @description Exact version (CID) */
            output_cid?: string;
            /** @description Output reference (version-specific) */
            output_doc_id?: string;
            /** @description Collection name */
            output_type?: string;
            prompt_tokens?: number;
            /** @description Provider info */
            provider?: string;
            /** @description Timing */
            queue_seconds?: number;
            reasoning_tokens?: number;
            stage?: string;
            /** @description Status */
            success?: boolean;
            total_seconds?: number;
            total_tokens?: number;
        };
        "github_com_jackzampolin_shelf_internal_providers.RateLimiterStatus": {
            last_429_time?: string;
            rps?: number;
            time_until_token?: components["schemas"]["time.Duration"];
            tokens_available?: number;
            total_consumed?: number;
            total_waited?: components["schemas"]["time.Duration"];
            utilization?: number;
        };
        "internal_server_endpoints.Book": {
            author?: string;
            created_at?: string;
            id?: string;
            page_count?: number;
            status?: string;
            title?: string;
        };
        "internal_server_endpoints.CreateJobRequest": {
            job_type?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        "internal_server_endpoints.CreateJobResponse": {
            id?: string;
        };
        "internal_server_endpoints.DefraStatus": {
            container?: string;
            health?: string;
            url?: string;
        };
        "internal_server_endpoints.ErrorResponse": {
            error?: string;
        };
        "internal_server_endpoints.GetJobResponse": {
            _docID?: string;
            completed_at?: string;
            created_at?: string;
            error?: string;
            job_type?: string;
            /** @description Live status fields (only populated for running jobs) */
            live_status?: {
                [key: string]: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
            pending_units?: number;
            progress?: {
                [key: string]: components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.ProviderProgress"];
            };
            started_at?: string;
            status?: components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.Status"];
            worker_status?: {
                [key: string]: components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.WorkerStatusInfo"];
            };
        };
        "internal_server_endpoints.GetPageResponse": {
            blend_confidence?: number;
            blend_markdown?: string;
            labels?: components["schemas"]["internal_server_endpoints.PageLabels"];
            ocr_results?: components["schemas"]["internal_server_endpoints.OcrResult"][];
            page_num?: number;
            status?: components["schemas"]["internal_server_endpoints.PageStatus"];
        };
        "internal_server_endpoints.HealthResponse": {
            defra?: string;
            status?: string;
        };
        "internal_server_endpoints.IngestRequest": {
            author?: string;
            pdf_paths?: string[];
            title?: string;
        };
        "internal_server_endpoints.IngestResponse": {
            author?: string;
            job_id?: string;
            status?: string;
            title?: string;
        };
        "internal_server_endpoints.JobStatusResponse": {
            blend_complete?: number;
            book_id?: string;
            is_complete?: boolean;
            job_type?: string;
            label_complete?: number;
            metadata_complete?: boolean;
            ocr_complete?: number;
            toc_extracted?: boolean;
            toc_found?: boolean;
            total_pages?: number;
        };
        "internal_server_endpoints.ListBooksResponse": {
            books?: components["schemas"]["internal_server_endpoints.Book"][];
        };
        "internal_server_endpoints.ListJobsResponse": {
            jobs?: components["schemas"]["github_com_jackzampolin_shelf_internal_jobs.Record"][];
        };
        "internal_server_endpoints.ListMetricsResponse": {
            count?: number;
            metrics?: components["schemas"]["github_com_jackzampolin_shelf_internal_metrics.Metric"][];
        };
        "internal_server_endpoints.ListPagesResponse": {
            pages?: components["schemas"]["internal_server_endpoints.PageSummary"][];
            total_pages?: number;
        };
        "internal_server_endpoints.MetricsCostResponse": {
            breakdown?: {
                [key: string]: number;
            };
            total_cost_usd?: number;
        };
        "internal_server_endpoints.MetricsSummaryResponse": {
            avg_cost_usd?: number;
            avg_time_seconds?: number;
            avg_tokens?: number;
            count?: number;
            error_count?: number;
            success_count?: number;
            total_cost_usd?: number;
            total_time_seconds?: number;
            total_tokens?: number;
        };
        "internal_server_endpoints.OcrResult": {
            confidence?: number;
            provider?: string;
            text?: string;
        };
        "internal_server_endpoints.PageLabels": {
            is_back_matter?: boolean;
            is_front_matter?: boolean;
            is_toc_page?: boolean;
            page_number_label?: string;
            running_header?: string;
        };
        "internal_server_endpoints.PageStatus": {
            blend_complete?: boolean;
            extract_complete?: boolean;
            label_complete?: boolean;
            ocr_complete?: boolean;
        };
        "internal_server_endpoints.PageSummary": {
            blend_complete?: boolean;
            label_complete?: boolean;
            ocr_complete?: boolean;
            page_num?: number;
        };
        "internal_server_endpoints.ProvidersStatus": {
            llm?: string[];
            ocr?: string[];
        };
        "internal_server_endpoints.StartJobRequest": {
            /** @description Optional: defaults to "process-pages" */
            job_type?: string;
        };
        "internal_server_endpoints.StartJobResponse": {
            book_id?: string;
            job_id?: string;
            job_type?: string;
            status?: string;
        };
        "internal_server_endpoints.StatusResponse": {
            defra?: components["schemas"]["internal_server_endpoints.DefraStatus"];
            providers?: components["schemas"]["internal_server_endpoints.ProvidersStatus"];
            server?: string;
        };
        "internal_server_endpoints.UpdateJobRequest": {
            error?: string;
            metadata?: {
                [key: string]: unknown;
            };
            status?: string;
        };
        /**
         * Format: int64
         * @enum {integer}
         */
        "time.Duration": -9223372036854776000 | 9223372036854776000 | 1 | 1000 | 1000000 | 1000000000 | 60000000000 | 3600000000000;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
