from enum import Enum


class BlockType(str, Enum):
    # Front matter
    TITLE_PAGE = "TITLE_PAGE"
    COPYRIGHT = "COPYRIGHT"
    DEDICATION = "DEDICATION"
    TABLE_OF_CONTENTS = "TABLE_OF_CONTENTS"
    PREFACE = "PREFACE"
    FOREWORD = "FOREWORD"
    INTRODUCTION = "INTRODUCTION"

    # Main content structure
    PART_HEADING = "PART_HEADING"
    CHAPTER_HEADING = "CHAPTER_HEADING"
    SECTION_HEADING = "SECTION_HEADING"
    SUBSECTION_HEADING = "SUBSECTION_HEADING"
    SUBSUBSECTION_HEADING = "SUBSUBSECTION_HEADING"
    BODY = "BODY"
    QUOTE = "QUOTE"
    EPIGRAPH = "EPIGRAPH"

    # Notes and references
    FOOTNOTE = "FOOTNOTE"
    ENDNOTES = "ENDNOTES"
    BIBLIOGRAPHY = "BIBLIOGRAPHY"
    REFERENCES = "REFERENCES"
    INDEX = "INDEX"

    # Back matter
    EPILOGUE = "EPILOGUE"
    APPENDIX = "APPENDIX"
    GLOSSARY = "GLOSSARY"
    ACKNOWLEDGMENTS = "ACKNOWLEDGMENTS"

    # Metadata/navigation
    HEADER = "HEADER"
    FOOTER = "FOOTER"
    PAGE_NUMBER = "PAGE_NUMBER"

    # Special
    ILLUSTRATION_CAPTION = "ILLUSTRATION_CAPTION"
    CAPTION = "CAPTION"
    TABLE = "TABLE"
    MAP_LABEL = "MAP_LABEL"
    DIAGRAM_LABEL = "DIAGRAM_LABEL"
    PHOTO_CREDIT = "PHOTO_CREDIT"
    OCR_ARTIFACT = "OCR_ARTIFACT"
    OTHER = "OTHER"
