package tts_generate

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/jackzampolin/shelf/internal/defra"
	"github.com/jackzampolin/shelf/internal/home"
	"github.com/jackzampolin/shelf/internal/svcctx"
)

// Database operations

func (j *Job) ensureBookAudioRecord(ctx context.Context, client *defra.Client) error {
	// BookAudioID is always set by NewJob() - either from existing record or newly created
	// This just updates the started_at timestamp when the job actually starts running
	if j.State.BookAudioID == "" {
		return fmt.Errorf("BookAudioID not set - this should never happen")
	}
	if client == nil {
		return fmt.Errorf("defra client not available")
	}

	mutation := fmt.Sprintf(`mutation {
		update_BookAudio(filter: {_docID: {_eq: "%s"}}, input: {
			status: "generating"
			started_at: "%s"
		}) {
			_docID
		}
	}`, j.State.BookAudioID, time.Now().UTC().Format(time.RFC3339))

	_, err := client.Execute(ctx, mutation, nil)
	return err
}

func (j *Job) saveAudioSegment(ctx context.Context, client *defra.Client, chapterDocID string, chapterIdx, paragraphIdx int, result *SegmentResult, sourceText string) (string, error) {
	uniqueKey := fmt.Sprintf("%s:%s:%d", j.State.BookID, chapterDocID, paragraphIdx)
	format := j.State.Format
	if format == "" {
		format = "mp3_44100_128"
	}

	// Truncate source text for storage (keep first 500 chars for debugging)
	truncatedText := sourceText
	if len(truncatedText) > 500 {
		truncatedText = truncatedText[:500] + "..."
	}

	// Prefer direct write for low-latency segment completion.
	if client != nil {
		// Note: chapter_id is auto-generated by DefraDB for chapter: Chapter relationship
		mutation := fmt.Sprintf(`mutation {
			add_AudioSegment(input: {
				_bookID: "%s"
				unique_key: "%s"
				chapter_idx: %d
				paragraph_idx: %d
				audio_file: "%s"
				duration_ms: %d
				start_offset_ms: %d
				format: "%s"
				char_count: %d
				cost_usd: %f
				created_at: "%s"
			}) {
				_docID
			}
		}`,
			j.State.BookID,
			uniqueKey,
			chapterIdx,
			paragraphIdx,
			result.AudioFile,
			result.DurationMS,
			result.StartOffsetMS,
			format,
			result.CharCount,
			result.CostUSD,
			time.Now().UTC().Format(time.RFC3339),
		)

		resp, err := client.Execute(ctx, mutation, nil)
		if err != nil {
			return "", err
		}

		if created, ok := resp.Data["add_AudioSegment"].(map[string]any); ok {
			return getString(created, "_docID"), nil
		}
		if createdArr, ok := resp.Data["add_AudioSegment"].([]any); ok && len(createdArr) > 0 {
			if created, ok := createdArr[0].(map[string]any); ok {
				return getString(created, "_docID"), nil
			}
		}
		return "", nil
	}
	return "", fmt.Errorf("defra client not available")
}

func (j *Job) saveChapterAudio(ctx context.Context, client *defra.Client, chapterDocID string, chapterIdx int) error {
	progress := j.State.ChapterProgress[chapterDocID]
	if progress == nil {
		return fmt.Errorf("no progress for chapter %s", chapterDocID)
	}
	if client == nil {
		return fmt.Errorf("defra client not available")
	}

	uniqueKey := fmt.Sprintf("%s:%s", j.State.BookID, chapterDocID)
	format := j.State.Format
	if format == "" {
		format = "mp3_44100_128"
	}

	// Calculate totals
	totalChars := 0
	for _, seg := range progress.Segments {
		totalChars += seg.CharCount
	}

	// Check if ChapterAudio already exists (for idempotent resume)
	existingDocID := ""
	if progress.ChapterAudioID != "" {
		existingDocID = progress.ChapterAudioID
	} else {
		// Query for existing record by unique_key
		query := fmt.Sprintf(`{
			ChapterAudio(filter: {unique_key: {_eq: "%s"}}) {
				_docID
			}
		}`, uniqueKey)
		resp, err := client.Execute(ctx, query, nil)
		if err == nil {
			if records, ok := resp.Data["ChapterAudio"].([]any); ok && len(records) > 0 {
				if record, ok := records[0].(map[string]any); ok {
					existingDocID = getString(record, "_docID")
					progress.ChapterAudioID = existingDocID
				}
			}
		}
	}

	// Use update if record exists, create otherwise
	if existingDocID != "" {
		mutation := fmt.Sprintf(`mutation {
			update_ChapterAudio(filter: {_docID: {_eq: "%s"}}, input: {
				audio_file: "%s"
				duration_ms: %d
				segment_count: %d
				total_char_count: %d
				total_cost_usd: %f
			}) {
				_docID
			}
		}`,
			existingDocID,
			progress.AudioFile,
			progress.TotalDurationMS,
			progress.CompletedSegments,
			totalChars,
			progress.TotalCostUSD,
		)

		_, err := client.Execute(ctx, mutation, nil)
		return err
	}

	// Create new record
	// Note: chapter_id is auto-generated by DefraDB for chapter: Chapter relationship
	// Use unique_key for lookups instead
	mutation := fmt.Sprintf(`mutation {
		add_ChapterAudio(input: {
			_bookID: "%s"
			unique_key: "%s"
			chapter_idx: %d
			audio_file: "%s"
			duration_ms: %d
			format: "%s"
			segment_count: %d
			total_char_count: %d
			total_cost_usd: %f
			created_at: "%s"
		}) {
			_docID
		}
	}`,
		j.State.BookID,
		uniqueKey,
		chapterIdx,
		progress.AudioFile,
		progress.TotalDurationMS,
		format,
		progress.CompletedSegments,
		totalChars,
		progress.TotalCostUSD,
		time.Now().UTC().Format(time.RFC3339),
	)

	resp, err := client.Execute(ctx, mutation, nil)
	if err != nil {
		return err
	}

	if createdArr, ok := resp.Data["add_ChapterAudio"].([]any); ok && len(createdArr) > 0 {
		if created, ok := createdArr[0].(map[string]any); ok {
			progress.ChapterAudioID = getString(created, "_docID")
		}
	} else if created, ok := resp.Data["add_ChapterAudio"].(map[string]any); ok {
		progress.ChapterAudioID = getString(created, "_docID")
	}

	return nil
}

func (j *Job) updateBookAudioComplete(ctx context.Context, client *defra.Client) error {
	if j.State.BookAudioID == "" {
		return nil
	}
	if client == nil {
		return fmt.Errorf("defra client not available")
	}

	mutation := fmt.Sprintf(`mutation {
		update_BookAudio(filter: {_docID: {_eq: "%s"}}, input: {
			status: "complete"
			completed_at: "%s"
			total_duration_ms: %d
			segment_count: %d
			total_cost_usd: %f
		}) {
			_docID
		}
	}`,
		j.State.BookAudioID,
		time.Now().UTC().Format(time.RFC3339),
		j.State.TotalDurationMS,
		j.State.CompletedSegments,
		j.State.TotalCostUSD,
	)

	_, err := client.Execute(ctx, mutation, nil)
	return err
}

func (j *Job) updateBookAudioFailed(ctx context.Context, client *defra.Client, cause error) error {
	if j.State.BookAudioID == "" {
		return nil
	}

	errMsg := ""
	if cause != nil {
		errMsg = cause.Error()
		if len(errMsg) > 2000 {
			errMsg = errMsg[:1997] + "..."
		}
	}

	if client == nil {
		return fmt.Errorf("defra client not available")
	}

	mutation := fmt.Sprintf(`mutation {
		update_BookAudio(filter: {_docID: {_eq: "%s"}}, input: {
			status: "failed"
			error_message: %q
			completed_at: "%s"
			total_duration_ms: %d
			segment_count: %d
			total_cost_usd: %f
		}) {
			_docID
		}
	}`,
		j.State.BookAudioID,
		errMsg,
		time.Now().UTC().Format(time.RFC3339),
		j.State.TotalDurationMS,
		j.State.CompletedSegments,
		j.State.TotalCostUSD,
	)

	_, err := client.Execute(ctx, mutation, nil)
	return err
}

func (j *Job) markBookAudioFailed(ctx context.Context, client *defra.Client, cause error) {
	if err := j.updateBookAudioFailed(ctx, client, cause); err != nil {
		if logger := svcctx.LoggerFrom(ctx); logger != nil {
			logger.Error("failed to update BookAudio failure status", "error", err)
		}
	}
}

// ConcatenateChapterAudio concatenates segment audio files into chapter audio.
// This is called by the CPU worker pool when processing concatenation work units.
func ConcatenateChapterAudio(ctx context.Context, bookID, chapterDocID string, homeDir *home.Dir, format string) (string, error) {
	if format == "" {
		format = "mp3_44100_128"
	}

	// Extract container extension from format (e.g., "mp3" from "mp3_44100_128")
	ext := formatToExtension(format)

	chapterDir := homeDir.ChapterAudioDir(bookID, chapterDocID)
	outputPath := homeDir.ChapterAudioPath(bookID, chapterDocID, format)

	// Find all segment files in order
	entries, err := os.ReadDir(chapterDir)
	if err != nil {
		return "", fmt.Errorf("failed to read chapter directory: %w", err)
	}

	var segmentFiles []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if filepath.Ext(name) == "."+ext {
			segmentFiles = append(segmentFiles, filepath.Join(chapterDir, name))
		}
	}

	if len(segmentFiles) == 0 {
		return "", fmt.Errorf("no segment files found in %s", chapterDir)
	}

	// Sort segment files by name (segment_0000, segment_0001, etc.)
	sort.Strings(segmentFiles)

	// Use ffmpeg to concatenate
	if err := concatenateWithFFmpeg(ctx, segmentFiles, outputPath); err != nil {
		return "", fmt.Errorf("ffmpeg concatenation failed: %w", err)
	}

	return outputPath, nil
}

// formatToExtension extracts the file extension from an ElevenLabs format string.
// e.g., "mp3_44100_128" -> "mp3", "wav_44100" -> "wav", "pcm_16000" -> "wav"
func formatToExtension(format string) string {
	if format == "" {
		return "mp3"
	}
	// Extract container format (before first underscore)
	for i, c := range format {
		if c == '_' {
			ext := format[:i]
			// PCM/ulaw/alaw are raw formats, use wav extension
			if ext == "pcm" || ext == "ulaw" || ext == "alaw" {
				return "wav"
			}
			return ext
		}
	}
	// No underscore, use as-is (legacy format like "mp3")
	return format
}
