package tts_generate

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/jackzampolin/shelf/internal/defra"
	"github.com/jackzampolin/shelf/internal/home"
	"github.com/jackzampolin/shelf/internal/svcctx"
)

// newTestJob builds a minimal Job with one chapter and one segment.
func newTestJob(t *testing.T, jobType string) *Job {
	t.Helper()
	return newTestJobWithChapters(t, jobType, 1, 1)
}

// newTestJobWithChapters builds a Job with the given number of chapters,
// each containing segmentsPerChapter paragraphs of polished text.
func newTestJobWithChapters(t *testing.T, jobType string, chapterCount, segmentsPerChapter int) *Job {
	t.Helper()

	paragraphs := make([]string, 0, segmentsPerChapter)
	for i := 0; i < segmentsPerChapter; i++ {
		paragraphs = append(paragraphs, fmt.Sprintf("Paragraph number %d.", i))
	}

	chapters := make([]*Chapter, 0, chapterCount)
	for i := 0; i < chapterCount; i++ {
		chapters = append(chapters, &Chapter{
			DocID:        fmt.Sprintf("chapter-%d", i),
			ChapterIdx:   i,
			PolishedText: strings.Join(paragraphs, "\n\n"),
		})
	}

	j, err := NewJobFromState(jobType, &AudioState{
		BookID:   "book-test",
		Chapters: chapters,
	})
	if err != nil {
		t.Fatalf("NewJobFromState(%s): %v", jobType, err)
	}
	return j
}

func TestStrategyIdentity(t *testing.T) {
	cases := []struct {
		jobType, provider, concat string
	}{
		{JobTypeElevenLabs, "elevenlabs", "concatenate_chapter"},
		{JobTypeOpenAI, "openai", "concatenate_chapter_openai"},
	}
	for _, c := range cases {
		s, err := strategyForJobType(c.jobType)
		if err != nil {
			t.Fatalf("%s: %v", c.jobType, err)
		}
		if s.Provider() != c.provider || s.JobType() != c.jobType || s.ConcatTaskName() != c.concat {
			t.Errorf("%s: got (%s,%s,%s)", c.jobType, s.Provider(), s.JobType(), s.ConcatTaskName())
		}
	}
	if _, err := strategyForJobType("bogus"); err == nil {
		t.Error("expected error for unknown job type")
	}
}

func TestJobReportsPersistedType(t *testing.T) {
	for _, jt := range []string{JobTypeElevenLabs, JobTypeOpenAI} {
		j := newTestJob(t, jt) // helper: minimal Job with one chapter, one segment
		if j.Type() != jt {
			t.Errorf("Type() = %s, want %s", j.Type(), jt)
		}
		if m := j.MetricsFor(); m.Stage != jt {
			t.Errorf("MetricsFor().Stage = %s, want %s", m.Stage, jt)
		}
	}
}

func TestElevenLabsQueuesOneSegmentPerChapter(t *testing.T) {
	j := newTestJobWithChapters(t, JobTypeElevenLabs, 2 /*chapters*/, 3 /*segments each*/)
	units := j.strategy.InitialWorkUnits(j)
	if len(units) != 2 {
		t.Fatalf("got %d initial units, want 2 (one per chapter)", len(units))
	}
}

func TestOpenAIQueuesAllSegments(t *testing.T) {
	j := newTestJobWithChapters(t, JobTypeOpenAI, 2, 3)
	units := j.strategy.InitialWorkUnits(j)
	if len(units) != 6 {
		t.Fatalf("got %d initial units, want 6 (all segments)", len(units))
	}
}

func TestOpenAISegmentCap(t *testing.T) {
	s, _ := strategyForJobType(JobTypeOpenAI)
	long := strings.Repeat("A sentence here. ", 600) // > 4096 chars
	for i, seg := range s.SegmentText(long) {
		if len(seg) > 4096 {
			t.Errorf("segment %d is %d chars, exceeds OpenAI 4096 cap", i, len(seg))
		}
	}
}

func TestResolvePairing(t *testing.T) {
	cases := []struct {
		jobType, cfgProvider, wantProvider string
		wantErr                            bool
	}{
		{JobTypeElevenLabs, "", "elevenlabs", false}, // empty resolves from job type
		{JobTypeElevenLabs, "elevenlabs", "elevenlabs", false},
		{JobTypeElevenLabs, "openai", "", true}, // mismatch rejected
		{JobTypeOpenAI, "", "openai", false},
		{JobTypeOpenAI, "openai", "openai", false},
		{JobTypeOpenAI, "elevenlabs", "", true},
		{"bogus", "", "", true},
	}
	for _, c := range cases {
		s, provider, err := resolvePairing(c.jobType, c.cfgProvider)
		if c.wantErr {
			if err == nil {
				t.Errorf("(%s,%s): want error", c.jobType, c.cfgProvider)
			}
			continue
		}
		if err != nil {
			t.Fatalf("(%s,%s): %v", c.jobType, c.cfgProvider, err)
		}
		if provider != c.wantProvider || s.Provider() != c.wantProvider {
			t.Errorf("(%s,%s): provider %q / strategy %q, want %q",
				c.jobType, c.cfgProvider, provider, s.Provider(), c.wantProvider)
		}
	}
}

// TestResumeRejectsMismatchedBookAudioProvider seeds a fake DefraDB so
// loadBookAudio returns a BookAudio generated by "openai", then constructs via
// the real NewJob as tts-generate (pinned to elevenlabs). NewJob must fail
// with a pairing error, not run the wrong orchestration.
func TestResumeRejectsMismatchedBookAudioProvider(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		w.Header().Set("Content-Type", "application/json")
		q := string(body)
		switch {
		case strings.Contains(q, "BookAudio("):
			io.WriteString(w, `{"data":{"BookAudio":[{"_docID":"audio-1","status":"generating","provider":"openai","voice":"onyx","format":"mp3","total_duration_ms":0,"chapter_count":1,"segment_count":0,"total_char_count":0,"total_cost_usd":0}]}}`)
		case strings.Contains(q, "Chapter("):
			io.WriteString(w, `{"data":{"Chapter":[{"_docID":"ch-1","entry_id":"e1","title":"One","level":1,"level_name":"chapter","entry_number":"1","matter_type":"body","audio_include":true,"polished_text":"Hello world.","sort_order":1,"polish_complete":true}]}}`)
		default:
			io.WriteString(w, `{"data":{"Book":[{"_docID":"book-1","title":"T","author":"A","status":"complete"}]}}`)
		}
	}))
	defer server.Close()

	h, err := home.New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	ctx := svcctx.WithServices(context.Background(), &svcctx.Services{
		DefraClient: defra.NewClient(server.URL),
		Home:        h,
	})

	_, err = NewJob(ctx, JobTypeElevenLabs, Config{}, "book-1")
	if err == nil {
		t.Fatal("want pairing error resuming elevenlabs job over openai BookAudio, got nil")
	}
	for _, want := range []string{"openai", "elevenlabs"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q should name provider %q", err, want)
		}
	}
}
